embeded functions
embeded functions/debug info

diff --git a/compiler/ETL/etl-i b/compiler/ETL/etl-i
--- a/compiler/ETL/etl-i
+++ b/compiler/ETL/etl-i
@@ -6,6 +6,13 @@ if [[ -z "$1" || ! -f "$1" ]]; then
   exit 1
 fi
 
+# Set debug info if the second argument is "-d"
+if [[ "$2" == "-d" ]]; then
+  debug_info="-d"
+else
+  debug_info=""
+fi
+
 # Get the base name
 base_name=$(basename "$1" .e)
 
@@ -13,4 +20,4 @@ base_name=$(basename "$1" .e)
 cc -x c -E "$1" -o "${base_name}.i" || { echo "Preprocessing failed"; exit 1; }
 
 # Run ETL_C with preprocessed file
-ETL_C -i "${base_name}.i" -e || { echo "ETL_C command failed"; exit 1; }
+ETL_C -i "${base_name}.i" -e "$debug_info" || { echo "ETL_C command failed"; exit 1; }
